local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.git_files, {})
vim.keymap.set("n", "<leader>pg", builtin.find_files, {})
vim.keymap.set("n", "<leader>fb", builtin.buffers, {})
vim.keymap.set("n", "<F1>", builtin.help_tags, {})
vim.keymap.set("n", "<leader>c", builtin.git_commits, {})
vim.keymap.set("n", "<leader>s", builtin.git_status, {})
vim.keymap.set("n", "<leader>j", builtin.jumplist, {})
vim.keymap.set("n", "<leader>r", builtin.lsp_references, {})

