-- return {
--     'akinsho/flutter-tools.nvim',
--     lazy = false,
--     dependencies = {
--         'nvim-lua/plenary.nvim',
--         'stevearc/dressing.nvim', -- optional for vim.ui.select
--     },
--     opts = {
--         debugger = {
--             enable = true,
--             run_via_dap = true,
--         },
--     }
-- }
